### ISSUE TITLE
Running the app - setting up the profiles.clj

### ISSUE THREAD

**Issue by Okwori** [anxolerd/rusty-leopard#1]
@anxolerd can you paste the content of your profiles.clj _(without the sensitive details of course)_, I am having issues setting up one and not the sure the version of Luminous this is.

**Comment by anxolerd** [comment]
Hi, @Okwori,

Unfortunately I currently have no access to the computer, on which the project was running, so I cannot share the file right now. On the other hand, as I recall and see in the code, you can run the project without `profiles.clj`, just by setting `JDBC_DATABASE_URL` environmental variable, like described here: https://jdbc.postgresql.org/documentation/head/connect.html

```bash
export JDBC_DATABASE_URL='jdbc:postgresql://localhost/mydb'
lein run
```


As for more concrete and full answer, I'll be able to give it in ~1 week, if you will still need it.

**Comment by Okwori** [comment]
Thanks, @anxolerd,

I actually meant to post that issue on https://github.com/cnirrad/lacinia-test which used the Luminous template. 

However, nice sample project. Really helpful...

**Comment by anxolerd** [comment]
@Okwori , as I promised, here are the contents of my `profiles.clj` file (_without the sensitive details of course_):

```clj
{:dev {:env {:db-uri "jdbc:postgresql://hostname:5432/dbname?user=user&password=s3kr3t"}}}
```

As addition to my previous reply, I just figured out, that you can either set `JDBC_DATABASE_URL` or `DB_URI` environmental variable for this purpose. If you set both, `DB_URI` takes precedence.

**Comment by Okwori** [comment]
Cool... Thanks man
